HTTP.Server Middleware
is-tech-y24-1/Do-Svyazi.Message pull request #34
Opened 2022-06-02 19:28 UTC by luck-o-o-luck

closes #29

2022-06-02 19:33 UTC, ronimizy requested changes

2022-06-02 19:33 UTC, ronimizy commented on Source/Presentation/Server/Do-Svyazi.Message.Server.Http/Middlewares/AuthenticationMiddleware.cs
> +        if (token != null)
```suggestion
        if (token is not null)
```

2022-06-02 19:33 UTC, ronimizy requested changes

2022-06-02 19:33 UTC, ronimizy commented on Source/Presentation/Server/Do-Svyazi.Message.Server.Http/Middlewares/AuthenticationMiddleware.cs
> +        var user = response.Result.UserModel;
https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/concepts/async/

2022-06-02 19:37 UTC, luck-o-o-luck commented on Source/Presentation/Server/Do-Svyazi.Message.Server.Http/Middlewares/AuthenticationMiddleware.cs
> +        var user = response.Result.UserModel;
а ой

2022-06-03 05:02 UTC, ronimizy requested changes

2022-06-03 05:02 UTC, ronimizy commented on Source/Application/Do-Svyazi.Message.Application.Abstractions/Exceptions/Unauthorized/AuthenticationException.cs
> +        : base("User is not touched") { }
Кого "touched"? За домогательства сядешь. "Attached".

2022-06-03 05:02 UTC, ronimizy commented on Source/Application/Do-Svyazi.Message.Application.Abstractions/Exceptions/Unauthorized/AuthenticationException.cs
> +    public AuthenticationException()
UnauthenticatedException

2022-06-03 07:30 UTC, ronimizy approved these changes

2022-06-03 07:52 UTC, ronimizy approved these changes

2022-06-03 07:53 UTC, merged