feat: rollback
is-tech-y24-1/Do-Svyazi.Message pull request #35
Opened 2022-06-02 20:03 UTC by kutuzovmikv

Closes #8

2022-06-02 22:43 UTC, luck-o-o-luck commented
![image](https://user-images.githubusercontent.com/78821666/171750211-daa5f545-d0f4-46a5-b3ad-fd5c8946da7e.png)
блин жаль

2022-06-03 19:32 UTC, ronimizy commented on Source/Presentation/Server/Do-Svyazi.Message.Server.Tcp/Filters/ExceptionFilter.cs
> +            await client.SendAsync("ReceiveAsync", e.Message);
Я бы поменял на что-то типа `"OnErrorAsync"`

2022-06-04 15:21 UTC, ronimizy requested changes

2022-06-04 15:21 UTC, ronimizy commented on Source/Presentation/Server/Do-Svyazi.Message.Server.Tcp/Authentication/ChatAuthHandler.cs
> +public class ChatAuthHandler : AuthenticationHandler<ChatAuthSchemeOptions>
`MessageAuthenticationHandler`

2022-06-04 15:21 UTC, ronimizy commented on Source/Presentation/Server/Do-Svyazi.Message.Server.Tcp/Authentication/ChatAuthHandler.cs
> +    }
Не вижу смысла в Try паттерне, если не подразумевается ошибка

2022-06-04 15:21 UTC, ronimizy commented on Source/Presentation/Server/Do-Svyazi.Message.Server.Tcp/Authentication/ChatAuthHandler.cs
> +        var claims = new[] {new Claim(ClaimTypes.NameIdentifier, userId.Result)}; // не уверен как правильно
опять синхронный доступ к результату таски...
разверни инициализацию массива на несколько строк

2022-06-04 15:21 UTC, ronimizy commented on Source/Presentation/Server/Do-Svyazi.Message.Server.Tcp/Authentication/ChatAuthHandler.cs
> +        ticket = new AuthenticationTicket(new ClaimsPrincipal(identity), Scheme.Name);
объяви `ClaimsPrincipal` на отдельной строке

2022-06-04 15:21 UTC, ronimizy commented on Source/Presentation/Server/Do-Svyazi.Message.Server.Tcp/Authentication/ChatAuthSchemeOptions.cs
> +}
форматни файл

2022-06-04 15:21 UTC, ronimizy commented on Source/Presentation/Server/Do-Svyazi.Message.Server.Tcp/Filters/AuthentificationFilter.cs
> +    }
Здесь ты выполняешь уже то, что сделал в AuthHandler, у контекста есть свойство User, в нём лежат клеймы, а именно тот клейм с идентификатором, что ты добавлял в AuthHandler

2022-06-04 15:21 UTC, ronimizy commented on Source/Presentation/Server/Do-Svyazi.Message.Server.Tcp/Providers/ChatUserIdProvider.cs
> +        throw new NotImplementedException();
тут тоже из клеймов достань айдишник

2022-06-07 18:12 UTC, ronimizy requested changes

2022-06-07 18:12 UTC, ronimizy commented on Source/Presentation/Server/Do-Svyazi.Message.Server.Tcp/Authentication/MessageAuthenticationHandler.cs
> +            return await Task.FromResult(AuthenticateResult.Fail(message));
Можно просто вернуть `AuthenticationResult`

2022-06-07 18:12 UTC, ronimizy commented on Source/Presentation/Server/Do-Svyazi.Message.Server.Tcp/Filters/AuthenticationFilter.cs
> +        var user = response.UserModel;
1. Ты уже стучался с этой квери, создай объект `UserModel` сам
2. Ты передаёшь айдишник туда где надо токен

2022-06-08 12:03 UTC, ronimizy commented on Source/Presentation/Server/Do-Svyazi.Message.Server.Tcp/Authentication/MessageAuthenticationHandler.cs
> +        );
Вынеси `ClaimsPrincipal` в отдельную переменную.

2022-06-08 13:37 UTC, merged